// Скрипт для заполнения БД тестовыми ВУЗами Казахстана
// Запускать из папки backend: node seed_universities.js

const mongoose = require('mongoose');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env') });

const University = require('./models/University');

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ Подключились к MongoDB');

    const universities = [
      {
        name: 'Атырауский университет нефти и газа',
        shortCode: 'AOGU',
        imageUrl: '/uploads/universities/aogu.jpg',
        city: 'АТЫРАУ',
        badgeText: 'Государственный',
        badgeIcon: 'fas fa-check-circle',
        grantMin: 65,
        priceFrom: 450000,
        tags: ['Общежитие', 'Военная кафедра'],
        majors: ['Нефть', 'Инженерия'],
        description: 'Ведущий технический университет Западного Казахстана для нефтегазовой отрасли.',
        address: 'г. Атырау, пр. Сатпаева, 1',
        phone: '+7 (7122) 35-12-34',
        email: 'info@aogu.kz',
        foundedYear: 1979,
        studentsCount: 8500,
        rating: 8.5,
        faculties: ['Нефтегазовый', 'Инженерии'],
        specialties: ['Нефтегазовое дело', 'Химическая технология'],
        dormitory: true,
        militaryDepartment: true,
        accreditation: 'Государственная',
        languages: ['Казахский', 'Русский'],
        website: 'https://aogu.kz'
      },
      {
        name: 'ЮКГУ им. М. Ауэзова',
        shortCode: 'SKSU',
        imageUrl: '/uploads/universities/sksu.jpg',
        city: 'ШЫМКЕНТ',
        badgeText: 'Многопрофильный',
        badgeIcon: 'fas fa-university',
        grantMin: 70,
        priceFrom: 350000,
        tags: ['Наука', 'Культура'],
        majors: ['IT', 'Химия', 'Педагогика'],
        description: 'Один из крупнейших вузов Южного Казахстана.',
        address: 'г. Шымкент, пр. Тауке хана, 5',
        phone: '+7 (7252) 12-34-56',
        foundedYear: 1943,
        studentsCount: 25000,
        rating: 8.0,
        dormitory: true,
        militaryDepartment: true,
        languages: ['Казахский', 'Русский'],
        website: 'https://auezov.edu.kz'
      },
      {
        name: 'КарТУ им. А. Сагинова',
        shortCode: 'KSTU',
        imageUrl: '/uploads/universities/kstu.jpg',
        city: 'КАРАГАНДА',
        badgeText: 'Технический лицей',
        badgeIcon: 'fas fa-cogs',
        grantMin: 80,
        priceFrom: 400000,
        tags: ['Инженерия', 'Горное дело'],
        majors: ['Машиностроение', 'IT'],
        description: 'Первый технический вуз Караганды.',
        address: 'г. Караганда, пр. Нурсултана Назарбаева, 56',
        phone: '+7 (7212) 56-12-34',
        foundedYear: 1953,
        studentsCount: 18000,
        rating: 8.7,
        dormitory: true,
        militaryDepartment: true,
        languages: ['Казахский', 'Русский'],
        website: 'https://kstu.kz'
      },
      {
        name: 'ЕНУ им. Л.Н. Гумилева',
        shortCode: 'ENU',
        imageUrl: '/uploads/universities/enu.jpg',
        city: 'АСТАНА',
        badgeText: 'Национальный',
        badgeIcon: 'fas fa-award',
        grantMin: 95,
        priceFrom: 650000,
        tags: ['Наука', 'Политика'],
        majors: ['Международные отношения', 'IT', 'Журналистика'],
        description: 'Главный национальный университет столицы.',
        address: 'г. Астана, ул. Сатпаева, 2',
        phone: '+7 (7172) 70-95-00',
        foundedYear: 1996,
        studentsCount: 20000,
        rating: 9.3,
        dormitory: true,
        militaryDepartment: true,
        languages: ['Казахский', 'Русский', 'Английский'],
        website: 'https://enu.kz'
      },
      {
        name: 'АРУ им. К. Жубанова',
        shortCode: 'AKU',
        imageUrl: '/uploads/universities/aku.jpg',
        city: 'АКТОБЕ',
        badgeText: 'Региональный',
        badgeIcon: 'fas fa-map-marker-alt',
        grantMin: 60,
        priceFrom: 320000,
        tags: ['Экономика', 'Медицина'],
        majors: ['Экономика', 'Педагогика'],
        address: 'г. Актобе, пр. А. Молдагуловой, 34',
        phone: '+7 (7132) 12-34-56',
        foundedYear: 1935,
        studentsCount: 15000,
        rating: 7.9,
        dormitory: true,
        militaryDepartment: true,
        languages: ['Казахский', 'Русский'],
        website: 'https://zhubanov.edu.kz'
      },
      {
        name: 'ВКТУ им. Д. Серикбаева',
        shortCode: 'EKTU',
        imageUrl: '/uploads/universities/ektu.jpg',
        city: 'УСТЬ-КАМЕНОГОРСК',
        badgeText: 'Инженерный лидер',
        badgeIcon: 'fas fa-tools',
        grantMin: 85,
        priceFrom: 480000,
        tags: ['Металлургия', 'IT'],
        majors: ['Машиностроение', 'IT'],
        address: 'г. Усть-Каменогорск, ул. Протозанова, 69',
        phone: '+7 (7232) 54-12-34',
        foundedYear: 1958,
        studentsCount: 12000,
        rating: 8.6,
        dormitory: true,
        militaryDepartment: true,
        languages: ['Казахский', 'Русский'],
        website: 'https://ektu.kz'
      },
      {
        name: 'Университет им. Шакарима',
        shortCode: 'SHAKU',
        imageUrl: '/uploads/universities/shaku.jpg',
        city: 'СЕМЕЙ',
        badgeText: 'Исторический',
        badgeIcon: 'fas fa-book',
        grantMin: 60,
        priceFrom: 300000,
        majors: ['Сельское хозяйство', 'Педагогика'],
        address: 'г. Семей, ул. Глинки, 20',
        foundedYear: 1934,
        studentsCount: 10000,
        rating: 7.5,
        dormitory: true,
        languages: ['Казахский', 'Русский'],
        website: 'https://shakarim.edu.kz'
      },
      {
        name: 'КУ им. Коркыт Ата',
        shortCode: 'KORKYT',
        imageUrl: '/uploads/universities/korkyt.jpg',
        city: 'КЫЗЫЛОРДА',
        badgeText: 'Областной центр',
        badgeIcon: 'fas fa-music',
        grantMin: 55,
        priceFrom: 280000,
        majors: ['Культура', 'Сельское хозяйство'],
        address: 'г. Кызылорда, пр. Абая, 66',
        foundedYear: 1937,
        studentsCount: 9000,
        rating: 7.3,
        dormitory: true,
        languages: ['Казахский', 'Русский'],
        website: 'https://korkyt.kz'
      },
      {
        name: 'МКТУ им. Х.А. Ясави',
        shortCode: 'IKTU',
        imageUrl: '/uploads/universities/iktu.jpg',
        city: 'ТУРКЕСТАН',
        badgeText: 'Международный Тюркский',
        badgeIcon: 'fas fa-star-and-crescent',
        grantMin: 80,
        priceFrom: 450000,
        tags: ['Медицина', 'Теология'],
        majors: ['Медицина', 'IT', 'Туризм'],
        address: 'г. Туркестан, пр. Б.Саттарханова, 29',
        foundedYear: 1991,
        studentsCount: 14000,
        rating: 8.4,
        dormitory: true,
        militaryDepartment: false,
        languages: ['Казахский', 'Турецкий', 'Русский'],
        website: 'https://ayu.edu.kz'
      },
      {
        name: 'КРУ им. А. Байтурсынова',
        shortCode: 'KRU',
        imageUrl: '/uploads/universities/kru.jpg',
        city: 'КОСТАНАЙ',
        badgeText: 'Аграрный хаб',
        badgeIcon: 'fas fa-seedling',
        grantMin: 58,
        priceFrom: 310000,
        majors: ['Сельское хозяйство', 'Ветеринария'],
        address: 'г. Костанай, ул. А. Байтурсынова, 47',
        foundedYear: 1939,
        studentsCount: 11000,
        rating: 7.6,
        dormitory: true,
        militaryDepartment: true,
        languages: ['Казахский', 'Русский'],
        website: 'https://ksu.edu.kz'
      },
      {
        name: 'ЗКУ им. М. Утемисова',
        shortCode: 'WKU',
        imageUrl: '/uploads/universities/wku.jpg',
        city: 'УРАЛЬСК',
        badgeText: 'Педагогический',
        badgeIcon: 'fas fa-pen-nib',
        grantMin: 62,
        priceFrom: 290000,
        majors: ['Педагогика', 'Музыка'],
        address: 'г. Уральск, ул. Н. Савичева, 44',
        foundedYear: 1932,
        studentsCount: 8000,
        rating: 7.4,
        dormitory: true,
        languages: ['Казахский', 'Русский'],
        website: 'https://wku.edu.kz'
      },
      {
        name: 'СКУ им. М. Козыбаева',
        shortCode: 'NKU',
        imageUrl: '/uploads/universities/nku.jpg',
        city: 'ПЕТРОПАВЛОВСК',
        badgeText: 'Северный хаб',
        badgeIcon: 'fas fa-snowflake',
        grantMin: 65,
        priceFrom: 330000,
        majors: ['Агрономия', 'IT'],
        address: 'г. Петропавловск, ул. Пушкина, 86',
        foundedYear: 1937,
        studentsCount: 7500,
        rating: 7.7,
        dormitory: true,
        militaryDepartment: true,
        languages: ['Казахский', 'Русский'],
        website: 'https://ku.edu.kz'
      },
      {
        name: 'КГУТИ им. Ш. Есенова',
        shortCode: 'YESSENOV',
        imageUrl: '/uploads/universities/yessenov.jpg',
        city: 'АКТАУ',
        badgeText: 'Морская академия',
        badgeIcon: 'fas fa-anchor',
        grantMin: 60,
        priceFrom: 340000,
        majors: ['Логистика', 'Нефть'],
        address: 'г. Актау, 32-й микрорайон',
        foundedYear: 1976,
        studentsCount: 7000,
        rating: 7.5,
        dormitory: true,
        militaryDepartment: false,
        languages: ['Казахский', 'Русский'],
        website: 'https://yu.edu.kz'
      },
      {
        name: 'Жетысуский университет им. И. Жансугурова',
        shortCode: 'ZHETSU',
        imageUrl: '/uploads/universities/zhetsu.jpg',
        city: 'ТАЛДЫКОРГАН',
        badgeText: 'Государственный',
        badgeIcon: 'fas fa-mountain',
        grantMin: 58,
        priceFrom: 295000,
        majors: ['Педагогика', 'Право'],
        address: 'г. Талдыкорган, ул. И. Жансугурова, 187',
        foundedYear: 1972,
        studentsCount: 6500,
        rating: 7.2,
        dormitory: true,
        languages: ['Казахский', 'Русский'],
        website: 'https://zhetysu.edu.kz'
      },
      {
        name: 'КУ им. Ш. Уалиханова',
        shortCode: 'KOKSHU',
        imageUrl: '/uploads/universities/kokshu.jpg',
        city: 'КОКШЕТАУ',
        badgeText: 'Региональный',
        badgeIcon: 'fas fa-check',
        grantMin: 62,
        priceFrom: 310000,
        majors: ['Медицина', 'Педагогика'],
        address: 'г. Кокшетау, ул. Абая, 76',
        foundedYear: 1962,
        studentsCount: 8000,
        rating: 7.6,
        dormitory: true,
        languages: ['Казахский', 'Русский'],
        website: 'https://shokan.edu.kz'
      },
      {
        name: 'КазНУ им. аль-Фараби',
        shortCode: 'KAZNU',
        imageUrl: '/uploads/universities/kaznu.jpg',
        city: 'АЛМАТЫ',
        badgeText: 'Топ-1 в СНГ',
        badgeIcon: 'fas fa-trophy',
        grantMin: 110,
        priceFrom: 1200000,
        tags: ['Наука', 'Международный'],
        majors: ['IT', 'Экономика', 'Право'],
        address: 'г. Алматы, пр. Аль-Фараби, 71',
        foundedYear: 1934,
        studentsCount: 20000,
        rating: 9.9,
        dormitory: true,
        militaryDepartment: true,
        languages: ['Казахский', 'Русский', 'Английский'],
        website: 'https://kaznu.kz'
      },
      {
        name: 'Назарбаев Университет',
        shortCode: 'NU',
        imageUrl: '/uploads/universities/nu.jpg',
        city: 'АСТАНА',
        badgeText: 'Элитный',
        badgeIcon: 'fas fa-crown',
        grantMin: 125,
        priceFrom: 0,
        tags: ['Исследования', 'Английский язык'],
        majors: ['IT', 'Наука', 'Инженерия'],
        address: 'г. Астана, пр. Кабанбай батыра, 53',
        foundedYear: 2010,
        studentsCount: 6000,
        rating: 10.0,
        dormitory: true,
        militaryDepartment: false,
        languages: ['Английский'],
        website: 'https://nu.edu.kz'
      }
    ];

    await University.deleteMany({});
    console.log('🧹 Коллекция universities очищена');

    await University.insertMany(universities);
    console.log(`✅ Залили ${universities.length} вуз(ов) в коллекцию!`);
  } catch (err) {
    console.error('❌ Ошибка:', err);
  } finally {
    await mongoose.disconnect();
    process.exit(0);
  }
}

seed();
